FROM postgres:11-alpine

RUN mkdir -p /tmp/psql_data/

COPY database/ipr_schema.postgres.sql /tmp/psql_data/ipr_schema.postgres.sql
COPY database/restore_iprschema_dump.sh /docker-entrypoint-initdb.d/
