FROM postgres:11-alpine

RUN mkdir -p /tmp/psql_data/

COPY ./database/iprdb_new_deployment.postgres.dump /tmp/psql_data/iprdb_new_deployment.postgres.dump
COPY ./database/restore_iprdb_dump.sh /docker-entrypoint-initdb.d/
