FROM postgres:13-alpine

RUN mkdir -p /tmp/psql_data/

COPY database/ipr_new_deployment.postgres.dump /tmp/psql_data/ipr_new_deployment.postgres.dump
COPY database/restore_iprdb_dump.sh /docker-entrypoint-initdb.d/
