IPR_DATABASE_PASSWORD=41p33@RG!
IPR_TESTING_PASSWORD=pol4rbe4r
IPR_GRAPHKB_PASSWORD=w4t3rm3l0n
IPR_EMAIL_PASSWORD='RR@24GzDMI'
IPR_EMAIL_EMAIL='PORIReportUpdates'
IPR_EMAIL_DOMAIN='@bcgsc.ca'
IPR_EMAIL_EHOST='webmail.bcgsc.ca'
