const express = require('express');

const summary = require('./summary');
const appendices = require('./appendices');
const copyVariants = require('./copyVariants');
const kbMatch = require('./kbMatch');
const probeResults = require('./probeResults');
const expressionVariants = require('./expressionVariants');
const proteinVariants = require('./proteinVariants');
const mavis = require('./mavis');
const presentation = require('./presentation');
const structuralVariants = require('./structuralVariants');
const smallMutations = require('./smallMutations');
const therapeuticTargets = require('./therapeuticTargets');
const probeTestInformation = require('./probeTestInformation');
const geneViewer = require('./geneViewer');
const gene = require('./gene');
const sampleInfo = require('./sampleInfo');
const mutationSignatures = require('./mutationSignatures');
const reportSignatures = require('./signatures');
const hlaTypes = require('./hlaTypes');
const pairwiseExpressionCorrelation = require('./pairwiseExpressionCorrelation');
const immuneCellTypes = require('./immuneCellTypes');
const mutationBurden = require('./mutationBurden');
const tmburMutationBurden = require('./tmburMutationBurden');
const comparators = require('./comparators');
const patientInformation = require('./patientInformation');
const images = require('./image');
const msi = require('./msi');
const signatureVariants = require('./signatureVariants');
const reportUser = require('./reportUser');
const variants = require('./variants');

const router = express.Router({mergeParams: true});

router.use('/summary', summary);
router.use('/image', images);

router.use('/appendices', appendices);
router.use('/copy-variants', copyVariants);
router.use('/expression-variants', expressionVariants);
router.use('/mavis', mavis);
router.use('/presentation', presentation);
router.use('/structural-variants', structuralVariants);
router.use('/small-mutations', smallMutations);
router.use('/mutation-signatures', mutationSignatures);
router.use('/mutation-burden', mutationBurden);
router.use('/tmbur-mutation-burden', tmburMutationBurden);
router.use('/therapeutic-targets', therapeuticTargets);
router.use('/signatures', reportSignatures);
router.use('/hla-types', hlaTypes);
router.use('/pairwise-expression-correlation', pairwiseExpressionCorrelation);
router.use('/immune-cell-types', immuneCellTypes);
router.use('/comparators', comparators);
router.use('/probe-test-information', probeTestInformation);
router.use('/kb-matches', kbMatch);
router.use('/probe-results', probeResults);
router.use('/gene-viewer', geneViewer);
router.use('/genes', gene);
router.use('/sample-info', sampleInfo);
router.use('/patient-information', patientInformation);
router.use('/msi', msi);
router.use('/signature-variants', signatureVariants);
router.use('/user', reportUser);
router.use('/variants', variants);
router.use('/protein-variants', proteinVariants);

module.exports = router;
